export const PALETTE = ["#C9A227", "#2F6F62", "#8A4B3B", "#4A5C8A", "#6B4E8A", "#3B7A57", "#A24E4E", "#4E7A8A"];

export const ink = "#1B1E24";
export const paper = "#EEF0F2";
export const paperCard = "#FFFFFF";
export const line = "#DADFE4";
export const gold = "#C9A227";
export const teal = "#2F6F62";

export const styles = {
  appShell: {
    display: "flex",
    minHeight: "100vh",
    width: "100%",
    background: paper,
    color: ink,
    fontFamily: "'Inter', sans-serif",
  },
  sidebar: {
    width: 220,
    background: ink,
    color: "#F2F1EC",
    display: "flex",
    flexDirection: "column",
    padding: "24px 16px",
    flexShrink: 0,
  },
  brand: { display: "flex", alignItems: "center", gap: 10, marginBottom: 28, padding: "0 8px" },
  brandMark: {
    width: 34,
    height: 34,
    borderRadius: 8,
    background: gold,
    color: ink,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 700,
    fontSize: 13,
    flexShrink: 0,
  },
  brandTitle: { fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 14, lineHeight: 1.3 },
  brandSub: { fontSize: 11, color: "#9BA3AE", marginTop: 1 },
  navList: { display: "flex", flexDirection: "column", gap: 4 },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 8,
    border: "none",
    background: "transparent",
    color: "#C3C8D1",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "inherit",
  },
  navItemActive: { background: "#2A2E37", color: "#FFFFFF" },
  main: { flex: 1, padding: "32px 40px", overflowY: "auto" },
  errorBanner: {
    background: "#F6E4E1",
    color: "#8A3B2E",
    padding: "10px 14px",
    borderRadius: 8,
    marginBottom: 16,
    fontSize: 13,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  errorClose: { background: "none", border: "none", cursor: "pointer", color: "#8A3B2E" },
  loadingWrap: { padding: 60, textAlign: "center", color: "#8A93A0", fontSize: 14 },
  pageHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", marginBottom: 24 },
  eyebrow: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 11,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#8A93A0",
    marginBottom: 4,
  },
  pageTitle: { fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 26, margin: 0 },
  weekNav: { display: "flex", alignItems: "center", gap: 6 },
  viewToggle: {
    display: "flex",
    border: `1px solid ${line}`,
    borderRadius: 8,
    overflow: "hidden",
    marginRight: 4,
  },
  viewToggleBtn: {
    padding: "0 12px",
    height: 32,
    border: "none",
    background: paperCard,
    fontSize: 12.5,
    fontWeight: 500,
    color: "#5A6270",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  viewToggleBtnActive: { background: ink, color: "#fff" },
  filterRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 16 },
  filterLabel: { fontSize: 12.5, color: "#8A93A0", fontWeight: 500 },
  conflictTag: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10,
    color: "#A24E4E",
    fontWeight: 600,
    marginBottom: 6,
  },
  monthGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 6,
  },
  monthWeekdayLabel: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10.5,
    color: "#8A93A0",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    textAlign: "center",
    padding: "0 0 4px",
  },
  monthCell: {
    background: paperCard,
    border: `1px solid ${line}`,
    borderRadius: 8,
    minHeight: 62,
    padding: 8,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "inherit",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  monthCellToday: { borderColor: gold, boxShadow: `0 0 0 1px ${gold}` },
  monthCellOutside: { opacity: 0.4 },
  monthCellHead: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  monthCellNum: { fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 13 },
  monthCellDots: { display: "flex", alignItems: "center", gap: 3, flexWrap: "wrap" },
  monthDot: { width: 6, height: 6, borderRadius: "50%" },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 8,
    border: `1px solid ${line}`,
    background: paperCard,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: ink,
  },
  todayBtn: {
    padding: "0 16px",
    height: 38,
    borderRadius: 8,
    border: `1px solid ${line}`,
    background: paperCard,
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    color: ink,
    fontFamily: "inherit",
  },
  primaryBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "9px 16px",
    borderRadius: 8,
    border: "none",
    background: ink,
    color: "#fff",
    fontSize: 13.5,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  ghostBtn: {
    padding: "9px 16px",
    borderRadius: 8,
    border: `1px solid ${line}`,
    background: "transparent",
    color: ink,
    fontSize: 13.5,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  dangerGhostBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "9px 14px",
    borderRadius: 8,
    border: "1px solid #E3B8B0",
    background: "transparent",
    color: "#A24E4E",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  weekGrid: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 10 },
  dayCol: {
    background: paperCard,
    borderRadius: 12,
    border: `1px solid ${line}`,
    padding: 10,
    minHeight: 260,
    display: "flex",
    flexDirection: "column",
  },
  dayColToday: { borderColor: gold, boxShadow: `0 0 0 1px ${gold}` },
  dayHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6 },
  dayName: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10.5,
    color: "#8A93A0",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  dayNum: { fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 18, marginTop: 1 },
  dayNumToday: { color: "#9A7A0E" },
  addDayBtn: {
    width: 30,
    height: 30,
    borderRadius: 7,
    border: "none",
    background: paper,
    color: ink,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  loadBarTrack: { height: 3, background: paper, borderRadius: 2, marginBottom: 10, overflow: "hidden" },
  loadBarFill: { height: "100%", background: teal, borderRadius: 2 },
  dayEvents: { display: "flex", flexDirection: "column", gap: 6, flex: 1 },
  absentRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 5,
    marginTop: 8,
    paddingTop: 8,
    borderTop: `1px dashed ${line}`,
  },
  absentNames: { fontSize: 11, color: "#9A6B4E", lineHeight: 1.4 },
  emptyDay: { color: "#C3C8D1", fontSize: 12, textAlign: "center", marginTop: 20 },
  eventCard: {
    position: "relative",
    background: paper,
    borderRadius: 8,
    overflow: "hidden",
  },
  eventCardMain: {
    display: "block",
    width: "100%",
    textAlign: "left",
    background: "transparent",
    border: "none",
    borderRadius: 8,
    padding: "7px 30px 7px 9px",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  eventShareBtn: {
    position: "absolute",
    top: 3,
    right: 3,
    width: 26,
    height: 26,
    borderRadius: 6,
    border: "none",
    background: "transparent",
    color: "#9AA2AC",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  shareChannelRow: { display: "flex", gap: 8, marginTop: 12 },
  shareChannelBtn: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    padding: "9px 10px",
    borderRadius: 8,
    border: `1px solid ${line}`,
    background: paperCard,
    color: ink,
    fontSize: 12.5,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
    textDecoration: "none",
  },
  shareHint: { fontSize: 11.5, color: "#8A93A0", marginTop: 8, lineHeight: 1.4 },
  eventTime: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10.5,
    color: "#6B7280",
    marginBottom: 2,
  },
  eventTitle: { fontSize: 12.5, fontWeight: 600, color: ink, lineHeight: 1.3 },
  eventLocation: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    fontSize: 10.5,
    color: "#6B7280",
    marginTop: 2,
  },
  noteCard: {
    textAlign: "left",
    background: "#F3EFE3",
    border: "none",
    borderRadius: 8,
    padding: "7px 9px",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  noteHead: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10,
    color: "#9A7A0E",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: 3,
  },
  noteText: { fontSize: 12, color: "#3A3F4A", lineHeight: 1.35, whiteSpace: "pre-wrap" },
  choiceCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 10,
    border: `1px solid ${line}`,
    background: paperCard,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "inherit",
    width: "100%",
  },
  choiceIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    background: paper,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    color: ink,
  },
  choiceLabel: { fontSize: 14, fontWeight: 600, color: ink },
  choiceDesc: { fontSize: 12, color: "#8A93A0", marginTop: 1 },
  avatarRow: { display: "flex", alignItems: "center", gap: 5, marginTop: 6 },
  avatarName: { fontSize: 11, color: "#5A6270", fontWeight: 500 },
  avatar: {
    width: 18,
    height: 18,
    borderRadius: "50%",
    color: "#fff",
    fontSize: 9,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  groupHead: { display: "flex", alignItems: "baseline", gap: 8, marginBottom: 12 },
  groupLabel: { fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 15 },
  groupCount: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 12, color: "#8A93A0" },
  emptyGroup: { color: "#8A93A0", fontSize: 13, padding: "8px 0" },
  peopleGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 10 },
  personCard: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: paperCard,
    border: `1px solid ${line}`,
    borderRadius: 10,
    padding: 10,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "inherit",
    width: "100%",
  },
  personAvatar: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    color: "#fff",
    fontWeight: 700,
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  personName: { fontSize: 13.5, fontWeight: 600, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  personMeta: { fontSize: 11.5, color: "#8A93A0", marginTop: 2 },
  absenceTag: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: "#9A6B4E",
    marginTop: 4,
  },
  absenceListItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: paperCard,
    border: `1px solid ${line}`,
    borderRadius: 8,
    padding: "8px 10px",
  },
  smallIconBtn: {
    width: 32,
    height: 32,
    borderRadius: 7,
    border: `1px solid ${line}`,
    background: "transparent",
    cursor: "pointer",
    fontSize: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: ink,
    flexShrink: 0,
  },
  smallIconBtnDanger: {
    width: 32,
    height: 32,
    borderRadius: 7,
    border: "1px solid #E3B8B0",
    background: "transparent",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#A24E4E",
    flexShrink: 0,
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(20,22,27,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    padding: 20,
  },
  modal: {
    background: paperCard,
    borderRadius: 14,
    width: 440,
    maxWidth: "100%",
    maxHeight: "90vh",
    overflowY: "auto",
    boxShadow: "0 20px 60px rgba(0,0,0,0.25)",
  },
  modalHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "18px 20px",
    borderBottom: `1px solid ${line}`,
  },
  modalTitle: { fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 16, margin: 0 },
  modalBody: { padding: 20 },
  modalFooter: { display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 4 },
  label: { display: "block", fontSize: 12, fontWeight: 600, color: "#5A6270", marginBottom: 6 },
  input: {
    width: "100%",
    padding: "9px 11px",
    borderRadius: 8,
    border: `1px solid ${line}`,
    fontSize: 13.5,
    fontFamily: "inherit",
    boxSizing: "border-box",
    color: ink,
  },
  segmented: { display: "flex", border: `1px solid ${line}`, borderRadius: 8, overflow: "hidden" },
  segBtn: {
    flex: 1,
    padding: "8px 0",
    border: "none",
    background: paperCard,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    color: "#5A6270",
    fontFamily: "inherit",
  },
  segBtnActive: { background: ink, color: "#fff" },
  colorRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  colorSwatch: { width: 26, height: 26, borderRadius: "50%", border: "none", cursor: "pointer" },
  assigneeGroupLabel: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10.5,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "#8A93A0",
    marginBottom: 5,
  },
  previewBox: {
    marginTop: 10,
    padding: "8px 10px",
    background: paper,
    borderRadius: 8,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  previewLine: { fontSize: 12.5, color: "#3A3F4A" },
  absentWarning: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11.5,
    color: "#A24E4E",
    marginTop: 2,
    marginBottom: 4,
  },
  assigneeList: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 8 },
  assigneeChip: {
    padding: "6px 12px",
    borderRadius: 20,
    border: `1px solid ${line}`,
    background: paperCard,
    fontSize: 12.5,
    fontWeight: 500,
    cursor: "pointer",
    color: ink,
    fontFamily: "inherit",
  },
  akteHead: { display: "flex", alignItems: "center", gap: 12, marginBottom: 18 },
  akteHeadCrew: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 11,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "#8A93A0",
  },
  akteDivider: { height: 1, background: line, margin: "18px 0" },
  akteSectionLabel: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 600,
    fontSize: 13.5,
    marginBottom: 10,
  },
  akteEventLine: { fontSize: 12.5, color: "#3A3F4A" },
  akteEventDate: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, color: "#8A93A0" },
  absenceForm: { background: paper, borderRadius: 10, padding: 12 },

  gateShell: {
    minHeight: "100vh",
    width: "100%",
    background: ink,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Inter', sans-serif",
    padding: 20,
  },
  gateCard: {
    background: "#20242C",
    borderRadius: 16,
    padding: 32,
    width: 360,
    maxWidth: "100%",
    color: "#F2F1EC",
  },
  gateMark: {
    width: 40,
    height: 40,
    borderRadius: 10,
    background: gold,
    color: ink,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 700,
    fontSize: 15,
    marginBottom: 18,
  },
  gateTitle: { fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 20, marginBottom: 6 },
  gateSub: { fontSize: 13, color: "#9BA3AE", marginBottom: 22, lineHeight: 1.5 },
  gateInput: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: 10,
    border: "1px solid #383D47",
    background: "#171A20",
    color: "#F2F1EC",
    fontSize: 15,
    fontFamily: "inherit",
    boxSizing: "border-box",
    marginBottom: 12,
    letterSpacing: "0.04em",
  },
  gateBtn: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: 10,
    border: "none",
    background: gold,
    color: ink,
    fontSize: 14.5,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  gateError: { fontSize: 12.5, color: "#E38B7E", marginBottom: 10 },
  pinRow: { display: "flex", gap: 10, justifyContent: "center", margin: "6px 0 4px" },
  pinBox: {
    width: 56,
    height: 64,
    borderRadius: 12,
    border: "1px solid #383D47",
    background: "#171A20",
    color: "#F2F1EC",
    fontSize: 28,
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 600,
    textAlign: "center",
    boxSizing: "border-box",
  },
  gateChip: {
    display: "block",
    width: "100%",
    padding: "12px 14px",
    borderRadius: 10,
    border: "1px solid #383D47",
    background: "#171A20",
    color: "#F2F1EC",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
    marginBottom: 8,
  },

  roleBadge: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "#8A93A0",
    padding: "3px 8px",
    border: "1px solid #383D47",
    borderRadius: 20,
    display: "inline-block",
  },
  logoutBtn: {
    marginTop: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 8,
    border: "none",
    background: "transparent",
    color: "#8A93A0",
    fontSize: 12.5,
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
  },
  readOnlyCard: { opacity: 0.85, cursor: "default" },
};
